### ISSUE TITLE
학생 리스트 표 스크롤이 안됩니다.

### ISSUE THREAD

**Issue by kmsgm** [wafflestudio/19.5-rookies#404]
안녕하세요, 코드를 수정하다가 문제가 생겨서 질문드립니다.
원래 학생 리스트 표에 학생을 추가할 때 표의 규격 안에 추가되어 스크롤이 가능한 방식으로 되어야 하는 것으로 알고 코드를 수정하기 전에는 잘 작동했습니다.

#### App.js (수정 전)
```
return (
        <table className="student-table">
            <thead>
                <tr className="table-header">
                <th className="header-name">이름</th>
                <th className="header-name">학년</th>
                </tr>
            </thead>
            <Student />
        </table>
```

#### StudentTable.js (수정 전)
```
return ( 
    <tbody className="table-content">
        {
            info.map((item, index) => {
                return (
                    <Student
                        key={index} 
                        item={item} 
                        handleRemove={handleRemove} 
                        handleEdit={handleEdit} 
                    />
                )
            })
        }
    </tbody>
);
````

위처럼 코드가 두 파일로 나뉘어져 있는 게 보기 좀 그래서 StudentTable.js 파일에 모두 집어넣었습니다.
#### StudentTable.js (수정 후)
```javascript
return (
    <table className="student-table">
        <thead>
            <tr className="table-header">
            <th className="header-name">이름</th>
            <th className="header-name">학년</th>
            </tr>
        </thead>
        <tbody className="table-content">
            {
                info.map((item, index) => {
                    return (
                        <Student
                            key={index} 
                            item={item} 
                            handleRemove={handleRemove} 
                            handleEdit={handleEdit} 
                        />
                    )
                })
            }
        </tbody>
    </table>
);
```

그런데 파일을 수정하고 난 뒤에 학생을 추가할 때 표 안에 추가되어 스크롤이 작용하는 것이 아니라 표 외관선을 위로 학생이 추가되어 스크롤이 작용하지 않을 뿐더러 엄청나게 이상한 모양이 만들어집니다...
css도 className에 맞춰서 그대로 가져왔기 때문에 뭐가 문제인지 모르겠어서 여기에 여쭤봅니다!

**Comment by woohm402** [comment]
스타일 관련 이슈가 이전에도 몇 번 있었는데, 리액트에서 스타일은 css가 담당하기 때문에 JS코드만으로는 원인을 찾을 수 없습니다. css부분은 어떻게 되어 있으신지, 엄청나게 이상한 모양은 어떻게 생겼는지 올려주시면 감사하겠습니다!

**Comment by woohm402** [comment]
추가로, ``` 이거만 작성하면 지금처럼 코드가 밋밋한데, ```javascript 이런 식으로 작성하면 코드가 예뻐집니다! 올려주신 코드 스니펫 중에 하나 수정해드렸는데 참고해주세요!

**Comment by kmsgm** [comment]
css 부분입니다!

```css
.student-table {
    position: absolute;
    width: calc(50% - 100px);
    height: 570px;
    left: 42px;
    top: 415px;
    overflow-y: scroll;
  
    border: 1px solid #C7C7C7;
    box-sizing: border-box;   
    border-collapse: collapse;
}

::-webkit-scrollbar {
    display: none;
}

.table-header {
    justify-content: space-between;
}

thead {
    position: absolute;
    width: 100%;
    height: 65px;
    left: 0px;
    top: 0px;
  
    background: #C4C4C4;
}
  
.header-name {
    font-size: 18px;
    /* top | right | bottom | left */
    padding: 20px 80px 15px 50px;
}

.table-content {
    position: absolute;
    width: 100%;
    height: 100%;
    left: 0px;
    top: 65px;
}
```
